....

diff --git a/moneymanagerex/PKGBUILD b/moneymanagerex/PKGBUILD
--- a/moneymanagerex/PKGBUILD
+++ b/moneymanagerex/PKGBUILD
@@ -1,10 +1,10 @@
 # Maintainer: Gyöngyösi Gábor <gabor at gshoots dot hu>
-# Based on the upstream MMEX build instructions and release tags.
+# Based on upstream MMEX build instructions and release tags.
 
 pkgname=moneymanagerex
 _pkgname=MoneyManagerEx
 pkgver=0
-pkgrel=1
+pkgrel=2
 pkgdesc="Easy-to-use personal finance application"
 arch=('x86_64')
 url="https://github.com/moneymanagerex/moneymanagerex"
@@ -20,10 +20,13 @@ depends=(
   'wxsqlite3'
   'wxwidgets-gtk3'
 )
+
 makedepends=(
+  'appstream'
   'cmake'
   'git'
 )
+
 optdepends=(
   'desktop-file-utils: desktop integration helpers'
   'shared-mime-info: MIME database updates'
@@ -70,7 +73,9 @@ pkgver() {
 }
 
 build() {
-  cmake -S "$srcdir/$pkgname" -B build \
+  cd "$srcdir/$pkgname"
+
+  cmake -S . -B build \
     -DCMAKE_BUILD_TYPE=Release \
     -DCMAKE_INSTALL_PREFIX=/usr \
     -DCMAKE_CXX_STANDARD=17
@@ -79,5 +84,27 @@ build() {
 }
 
 package() {
-  DESTDIR="$pkgdir" cmake --install build
+  cd "$srcdir/$pkgname"
+
+  local builddir="$srcdir/$pkgname/build"
+  local metainfo_in="resources/dist/linux/share/metainfo/org.moneymanagerex.MMEX.metainfo.xml.in"
+  local metainfo_out="$builddir/org.moneymanagerex.MMEX.metainfo.xml"
+
+  mkdir -p "$builddir"
+
+  if [[ ! -s "$metainfo_out" ]]; then
+    if command -v appstreamcli >/dev/null 2>&1 && [[ -f NEWS && -f "$metainfo_in" ]]; then
+      appstreamcli news-to-metainfo --format=markdown \
+        NEWS \
+        "$metainfo_in" \
+        "$metainfo_out" || install -Dm644 "$metainfo_in" "$metainfo_out"
+    elif [[ -f "$metainfo_in" ]]; then
+      install -Dm644 "$metainfo_in" "$metainfo_out"
+    else
+      echo "error: metainfo template not found: $metainfo_in" >&2
+      return 1
+    fi
+  fi
+
+  DESTDIR="$pkgdir" cmake --install "$builddir"
 }
