ADJUST sdwebui-forge

diff --git a/stable-diffusion-webui-forge/PKGBUILD b/stable-diffusion-webui-forge/PKGBUILD
--- a/stable-diffusion-webui-forge/PKGBUILD
+++ b/stable-diffusion-webui-forge/PKGBUILD
@@ -1,31 +1,64 @@
 # Maintainer: Gyöngyösi Gábor <gabor at gshoots dot hu>
 
-pkgname=stable-diffusion-webui-forge
+_pkgname="stable-diffusion-webui-forge"
+pkgname="${_pkgname}"
 pkgver=r0.0000000
 pkgrel=1
-pkgdesc="Stable Diffusion WebUI Forge (system-wide install for Manjaro ISO)"
+pkgdesc="Stable Diffusion WebUI Forge (main branch) - python310 runtime"
 arch=('x86_64')
 url="https://github.com/lllyasviel/stable-diffusion-webui-forge"
-license=('MIT')
-depends=('python310')
-backup=('opt/stable-diffusion-webui-forge/webui-user.sh')
-source=(
-  "stable-diffusion-webui-forge::git+https://github.com/lllyasviel/stable-diffusion-webui-forge.git#tag=v${pkgver}"
-  "stable-diffusion-webui-forge.service"
+license=('AGPL3')
+
+depends=(
+  'python310'
+  'git'
 )
-sha256sums=('SKIP' 'SKIP')
+
+makedepends=('git')
 
 install="${pkgname}.install"
 
+# FONTOS: ha user módosítja, update nem írhatja felül
+backup=("opt/${_pkgname}/webui-user.sh")
+
+source=(
+  "${pkgname}::git+${url}.git#branch=main"
+  "${pkgname}.service"
+)
+
+sha256sums=('SKIP' 'SKIP')
+
+_appdir="/opt/${_pkgname}"
+
+pkgver() {
+  cd "$srcdir/$pkgname"
+  printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
+}
+
 package() {
-  install -dm755 "${pkgdir}/opt"
-  cp -r "${srcdir}/stable-diffusion-webui-forge" \
-        "${pkgdir}/opt/stable-diffusion-webui-forge"
 
-  # model mappa (üresen, hogy ne törlődjön frissítéskor)
-  install -dm2775 "${pkgdir}/opt/stable-diffusion-webui-forge/models"
+  # systemd unit
+  install -Dm644 "$srcdir/${pkgname}.service" \
+    "$pkgdir/usr/lib/systemd/system/${pkgname}.service"
 
-  # service
-  install -Dm644 "${srcdir}/stable-diffusion-webui-forge.service" \
-    "${pkgdir}/usr/lib/systemd/system/stable-diffusion-webui-forge.service"
+  # app files
+  install -d "$pkgdir${_appdir}"
+  cp -a "$srcdir/$pkgname/." "$pkgdir${_appdir}/"
+  rm -rf "$pkgdir${_appdir}/.git"
+
+  # build-time patch of repo's own webui-user.sh
+  _cfg="$pkgdir${_appdir}/webui-user.sh"
+
+  if [[ -f "$_cfg" ]]; then
+    if grep -qE '^[[:space:]]*#?[[:space:]]*export[[:space:]]+COMMANDLINE_ARGS=' "$_cfg"; then
+      sed -i -E \
+        's|^[[:space:]]*#?[[:space:]]*export[[:space:]]+COMMANDLINE_ARGS=.*|export COMMANDLINE_ARGS="--opt-split-attention --disable-gpu-warning --port 7860 --api --skip-python-version-check"|' \
+        "$_cfg"
+    else
+      printf '\nexport COMMANDLINE_ARGS="--opt-split-attention --disable-gpu-warning --port 7860 --api --skip-python-version-check"\n' >> "$_cfg"
+    fi
+  else
+    echo "ERROR: webui-user.sh not found in repo root!"
+    exit 1
+  fi
 }
